# SPDX-FileCopyrightText: 2024 Dominik Wombacher <dominik@wombacher.cc>
#
# SPDX-License-Identifier: CC0-1.0

# builds.sr.ht - Build manifest
# https://man.sr.ht/builds.sr.ht/manifest.md

image: archlinux
packages:
  - podman
  - helm
sources:
  - https://git.sr.ht/~wombelix/chart-fluent-bit-syslog-to-aws-cloudtrail-data
  - https://git.sr.ht/~wombelix/build-helper-scripts
secrets:
  - f7847d8d-f3db-49d9-b4ce-d438a47db5ee
  - 5b076ab5-1361-4d71-905b-4ff8c836c62c
environment:
  GIT_MIRROR_SSH_KEY: ~/.ssh/5b076ab5-1361-4d71-905b-4ff8c836c62c
  GIT_MIRROR_GITHUB: git@github.com:wombelix/chart-fluent-bit-syslog-to-aws-cloudtrail-data.git
  GIT_MIRROR_GITLAB: git@gitlab.com:wombelix/chart-fluent-bit-syslog-to-aws-cloudtrail-data.git
  GIT_MIRROR_CODEBERG: git@codeberg.org:wombelix/chart-fluent-bit-syslog-to-aws-cloudtrail-data.git
tasks:
  - mirror: |
      cd build-helper-scripts
      source git-mirror.sh
      cd ..

      cd chart-fluent-bit-syslog-to-aws-cloudtrail-data

      git_mirror "$GIT_MIRROR_SSH_KEY" "$GIT_MIRROR_GITHUB"
      git_mirror "$GIT_MIRROR_SSH_KEY" "$GIT_MIRROR_GITLAB"
      git_mirror "$GIT_MIRROR_SSH_KEY" "$GIT_MIRROR_CODEBERG"

  - helm: |
      cd chart-fluent-bit-syslog-to-aws-cloudtrail-data

      GIT_SHA=$(git rev-parse --short HEAD)
      GIT_TAG=$(git tag --points-at=${GIT_SHA})
      if [ -n "${GIT_TAG}" ]; then
        helm package fluent-bit-syslog-to-aws-cloudtrail-data
      else
        sed -i "/^version/ s/$/-main+${GIT_SHA}/" fluent-bit-syslog-to-aws-cloudtrail-data/Chart.yaml
        helm package fluent-bit-syslog-to-aws-cloudtrail-data
      fi

      set +x
      helm --registry-config $HOME/.docker/config.json push fluent-bit-syslog-to-aws-cloudtrail-data-*.tgz oci://quay.io/wombelix
      set -x

triggers:
  - action: email
    condition: failure
    to: dominik@wombacher.cc
